# Generated by Django 4.2.5 on 2023-09-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MementoItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=128, verbose_name='item_name')),
                ('item_explanation', models.CharField(max_length=128, verbose_name='item_explanation')),
            ],
        ),
    ]
