# Generated by Django 5.0.6 on 2024-08-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mementoitems',
            name='item_explanation',
            field=models.CharField(max_length=1024, verbose_name='item_explanation'),
        ),
        migrations.AlterField(
            model_name='mementoitems',
            name='item_name',
            field=models.CharField(max_length=256, unique=True, verbose_name='item_name'),
        ),
    ]
