# Generated by Django 5.0.6 on 2024-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0002_alter_mementoitems_item_explanation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mementoitems',
            name='item_name',
            field=models.CharField(max_length=256),
        ),
    ]
