# Generated by Django 5.0.6 on 2024-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapi', '0005_todoitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitems',
            name='item_name',
            field=models.CharField(max_length=1024),
        ),
    ]
