# Generated by Django 5.0.6 on 2024-07-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='default_profile.jpg', upload_to='', verbose_name='photo de profil'),
        ),
    ]
