# Generated by Django 5.0.6 on 2024-09-11 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_subscriber_is_active_subscriber_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='static/img_home/'),
        ),
    ]
